### ISSUE TITLE
Ideas & todo

### ISSUE THREAD

**Issue by olaviinha** [olaviinha/SloppyButcher#1]
### Todo

- [ ] Put vol slider back

### Under consideration

- [ ] 1. Setting: beat slice
- [ ] 2. Conventional beat structure probability slider
- [ ] 3. Timestretch all audio source material to bpm
- [ ] 4. Autotune
- [ ] 5. Upload source material as zip
- [ ] 6. Multipattern tracking

#### 1. Setting: beat slice
- [ ] Beat slice tracks
- [ ] Trim beat-slices to new bpm

#### 2. Conventional beat structure probability slider
Increase/decrease the probability of kicks and snares hitting consecutively at odd and even pulses when using oneshot drums as audio source material.
- [ ] Fields for kick and snare file identifiers (e.g. "*kick*, *bd*; *sn*, *clap*).
- [ ] Separate files in slicing process (kicks, snares, rest).
- [ ] Fetch from correct slice set in concat process.

#### 3. Timestretch all audio source material to bpm
- [ ] Steady tempo estimation.
- [ ] Trim to first beat

#### 4. Autotune
- [ ] Slice pitch estimation
- [ ] Pitch slice to user-defined pitch setting from estimation.

#### 5. Upload source material as zip
- [ ] Ignore Google Drive integration
- [ ] Upload
- [ ] Extraction

#### 6. Multipattern tracking
- [x] Butcher multiple sets of audio source material separately in one go.
- [ ] Define which set of audio source material is used per pattern.
- [ ] Add more pattern-specific Settings.
- [ ] Warn if number of bars, repeats and patterns seems it might be unintentionally off.
- [ ] Concatenate patterns.
